sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dmitrymishanov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmitrymishanov/react-test npm test

after_success:
  - docker build -t dmitrymishanov/client ./client
  - docker build -t dmitrymishanov/server ./server
  - docker build -t dmitrymishanov/worker ./worker
  - docker build -t dmitrymishanov/nginx ./nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push dmitrymishanov/client
  - docker push dmitrymishanov/server
  - docker push dmitrymishanov/worker
  - docker push dmitrymishanov/nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
